
// <auto-generated />
#pragma warning disable
#nullable enable
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Reflection;
using HarmonyLib;
using MockMe;
using MockMe.Mocks;
using MockMe.Mocks.ClassMemberMocks;
using MockMe.Mocks.ClassMemberMocks.CallTracker;

namespace MockMe.Generated.MockMe.Tests.ExampleClasses
{
    public class Calculator
    {
        public int Add(int x, int y) => x + y;

        public double Multiply(double x, double y) => x * y;

        public CalculatorType CalculatorType { get; set; }

        public void DivideByZero(double numToDivide) =>
            throw new InvalidOperationException("Cannot divide by 0");

        public bool IsOn() => true;

        public void TurnOff() { }
    }

    public enum CalculatorType
    {
        Standard,
        Scientific,
        Graphing,
    }
    [global::System.CodeDom.Compiler.GeneratedCode("MockMe", "1.0.0.0")]
    internal class CalculatorMock
        : global::MockMe.Abstractions.SealedTypeMock<Calculator>
    {

        public CalculatorMock()
        {
            this.Setup = new CalculatorMockSetup();
            this.CallTracker = new CalculatorMockSetup.CalculatorMockCallTracker(this.Setup);
            this.Assert = new CalculatorMockSetup.CalculatorMockCallTracker.CalculatorMockAsserter(this.CallTracker);
            global::MockMe.MockStore<Calculator>.Store.TryAdd(this.MockedObject, this);
        }

        public CalculatorMockSetup Setup { get; }
        public CalculatorMockSetup.CalculatorMockCallTracker.CalculatorMockAsserter Assert { get; }
        private CalculatorMockSetup.CalculatorMockCallTracker CallTracker { get; }

        internal sealed class Patcha998d05b568441ffae20afbe87c8f103
        {
            private static bool Prefix(Calculator __instance, ref global::System.Int32 __result, global::System.Int32 x, global::System.Int32 y)
            {
                if (global::MockMe.MockStore<Calculator>.TryGetValue<CalculatorMock>(__instance, out var mock))
                {
                    __result = mock.CallTracker.Add(x, y);
                    return false;
                }

                return true;
            }
        }
        internal sealed class Patch8c3fd4577f8d462a86493c7c36f86cee
        {
            private static bool Prefix(Calculator __instance, ref global::System.Double __result, global::System.Double x, global::System.Double y)
            {
                if (global::MockMe.MockStore<Calculator>.TryGetValue<CalculatorMock>(__instance, out var mock))
                {
                    __result = mock.CallTracker.Multiply(x, y);
                    return false;
                }

                return true;
            }
        }
        internal sealed class Patch21cc0ea43c274fb9a3a046b77adc67e1
        {
            private static bool Prefix(Calculator __instance, ref CalculatorType __result)
            {
                if (global::MockMe.MockStore<Calculator>.TryGetValue<CalculatorMock>(__instance, out var mock))
                {
                    __result = mock.CallTracker.CalculatorType;
                    return false;
                }
                return true;
            }
        }

        internal sealed class Patch2df041c75c36424d9ff3c696a2d1de1d
        {
            private static bool Prefix(Calculator __instance, CalculatorType value)
            {
                if (global::MockMe.MockStore<Calculator>.TryGetValue<CalculatorMock>(__instance, out var mock))
                {
                    mock.CallTracker.CalculatorType = value;
                    return false;
                }
                return true;
            }
        }

        internal sealed class Patch997ac6d1203e4e939512e7603cad4a42
        {
            private static bool Prefix(Calculator __instance, global::System.Double numToDivide)
            {
                if (global::MockMe.MockStore<Calculator>.TryGetValue<CalculatorMock>(__instance, out var mock))
                {
                    mock.CallTracker.DivideByZero(numToDivide);
                    return false;
                }

                return true;
            }
        }
        internal sealed class Patch47541ab8e1984c08b7cca45a36e810ef
        {
            private static bool Prefix(Calculator __instance, ref global::System.Boolean __result)
            {
                if (global::MockMe.MockStore<Calculator>.TryGetValue<CalculatorMock>(__instance, out var mock))
                {
                    __result = mock.CallTracker.IsOn();
                    return false;
                }

                return true;
            }
        }
        internal sealed class Patcheec2cff683124024b98e047f693db80e
        {
            private static bool Prefix(Calculator __instance)
            {
                if (global::MockMe.MockStore<Calculator>.TryGetValue<CalculatorMock>(__instance, out var mock))
                {
                    mock.CallTracker.TurnOff();
                    return false;
                }

                return true;
            }
        }
        static CalculatorMock()
        {
            var harmony = new global::HarmonyLib.Harmony("com.mockme.patch");

            var originalPatcha998d05b568441ffae20afbe87c8f103 = typeof(Calculator).GetMethod("Add", new Type[] { typeof(global::System.Int32), typeof(global::System.Int32) });
            var Patcha998d05b568441ffae20afbe87c8f103 = typeof(Patcha998d05b568441ffae20afbe87c8f103).GetMethod("Prefix", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic);

            harmony.Patch(originalPatcha998d05b568441ffae20afbe87c8f103, prefix: new HarmonyMethod(Patcha998d05b568441ffae20afbe87c8f103));

            var originalPatch8c3fd4577f8d462a86493c7c36f86cee = typeof(Calculator).GetMethod("Multiply", new Type[] { typeof(global::System.Double), typeof(global::System.Double) });
            var Patch8c3fd4577f8d462a86493c7c36f86cee = typeof(Patch8c3fd4577f8d462a86493c7c36f86cee).GetMethod("Prefix", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic);

            harmony.Patch(originalPatch8c3fd4577f8d462a86493c7c36f86cee, prefix: new HarmonyMethod(Patch8c3fd4577f8d462a86493c7c36f86cee));

            var originalPatch21cc0ea43c274fb9a3a046b77adc67e1 = typeof(Calculator).GetMethod("get_CalculatorType", new Type[] { });
            var Patch21cc0ea43c274fb9a3a046b77adc67e1 = typeof(Patch21cc0ea43c274fb9a3a046b77adc67e1).GetMethod("Prefix", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic);

            harmony.Patch(originalPatch21cc0ea43c274fb9a3a046b77adc67e1, prefix: new HarmonyMethod(Patch21cc0ea43c274fb9a3a046b77adc67e1));

            var originalPatch2df041c75c36424d9ff3c696a2d1de1d = typeof(Calculator).GetMethod("set_CalculatorType", new Type[] { typeof(CalculatorType) });
            var Patch2df041c75c36424d9ff3c696a2d1de1d = typeof(Patch2df041c75c36424d9ff3c696a2d1de1d).GetMethod("Prefix", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic);

            harmony.Patch(originalPatch2df041c75c36424d9ff3c696a2d1de1d, prefix: new HarmonyMethod(Patch2df041c75c36424d9ff3c696a2d1de1d));

            var originalPatch997ac6d1203e4e939512e7603cad4a42 = typeof(Calculator).GetMethod("DivideByZero", new Type[] { typeof(global::System.Double) });
            var Patch997ac6d1203e4e939512e7603cad4a42 = typeof(Patch997ac6d1203e4e939512e7603cad4a42).GetMethod("Prefix", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic);

            harmony.Patch(originalPatch997ac6d1203e4e939512e7603cad4a42, prefix: new HarmonyMethod(Patch997ac6d1203e4e939512e7603cad4a42));

            var originalPatch47541ab8e1984c08b7cca45a36e810ef = typeof(Calculator).GetMethod("IsOn", new Type[] { });
            var Patch47541ab8e1984c08b7cca45a36e810ef = typeof(Patch47541ab8e1984c08b7cca45a36e810ef).GetMethod("Prefix", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic);

            harmony.Patch(originalPatch47541ab8e1984c08b7cca45a36e810ef, prefix: new HarmonyMethod(Patch47541ab8e1984c08b7cca45a36e810ef));

            var originalPatcheec2cff683124024b98e047f693db80e = typeof(Calculator).GetMethod("TurnOff", new Type[] { });
            var Patcheec2cff683124024b98e047f693db80e = typeof(Patcheec2cff683124024b98e047f693db80e).GetMethod("Prefix", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic);

            harmony.Patch(originalPatcheec2cff683124024b98e047f693db80e, prefix: new HarmonyMethod(Patcheec2cff683124024b98e047f693db80e));

        }

    }

    [global::System.CodeDom.Compiler.GeneratedCode("MockMe", "1.0.0.0")]
    internal class CalculatorMockSetup : global::MockMe.Mocks.ClassMemberMocks.Setup.MemberMockSetup
    {

        internal class Add_Int32_Int32Collection : OriginalArgBag<global::System.Int32, global::System.Int32>
        {
            public Add_Int32_Int32Collection(global::System.Int32 x, global::System.Int32 y) : base(x, y)
            { }
            public global::System.Int32 x { get => this.Arg1; set => this.Arg1 = value; }
            public global::System.Int32 y { get => this.Arg2; set => this.Arg2 = value; }
        }
        private List<ArgBagWithMock<Add_Int32_Int32Collection>>? Add_Int32_Int32BagStore;
        public global::MockMe.Mocks.ClassMemberMocks.MemberMock<Add_Int32_Int32Collection, global::System.Int32> Add(Arg<global::System.Int32> x, Arg<global::System.Int32> y)
        {

            return SetupMethod<Add_Int32_Int32Collection, MemberMock<Add_Int32_Int32Collection, int>>(this.Add_Int32_Int32BagStore ??= new(), new ArgBag<int, int>(x, y));
            ;
        }
        internal class Multiply_Double_DoubleCollection : OriginalArgBag<global::System.Double, global::System.Double>
        {
            public Multiply_Double_DoubleCollection(global::System.Double x, global::System.Double y) : base(x, y)
            { }
            public global::System.Double x { get => this.Arg1; set => this.Arg1 = value; }
            public global::System.Double y { get => this.Arg2; set => this.Arg2 = value; }
        }
        private List<ArgBagWithMock<Multiply_Double_DoubleCollection>>? Multiply_Double_DoubleBagStore;
        public global::MockMe.Mocks.ClassMemberMocks.MemberMock<Multiply_Double_DoubleCollection, global::System.Double> Multiply(Arg<global::System.Double> x, Arg<global::System.Double> y)
        {

            return SetupMethod(this.Multiply_Double_DoubleBagStore ??= new(), new(x, y));
            ;
        }
        internal class set_CalculatorType_CalculatorTypeCollection : OriginalArgBag<CalculatorType>
        {
            public set_CalculatorType_CalculatorTypeCollection(CalculatorType value) : base(value)
            { }
            public CalculatorType value { get => this.Arg1; set => this.Arg1 = value; }
        }
        internal class DivideByZero_DoubleCollection : OriginalArgBag<global::System.Double>
        {
            public DivideByZero_DoubleCollection(global::System.Double numToDivide) : base(numToDivide)
            { }
            public global::System.Double numToDivide { get => this.Arg1; set => this.Arg1 = value; }
        }
        private List<ArgBagWithMock<DivideByZero_DoubleCollection>>? DivideByZero_DoubleBagStore;
        public global::MockMe.Mocks.ClassMemberMocks.VoidMemberMock<DivideByZero_DoubleCollection> DivideByZero(Arg<global::System.Double> numToDivide)
        {

            return SetupMethod(this.DivideByZero_DoubleBagStore ??= new(), new(numToDivide));
            ;
        }
        private global::MockMe.Mocks.ClassMemberMocks.MemberMock<global::System.Boolean>? IsOn_BagStore;
        public global::MockMe.Mocks.ClassMemberMocks.MemberMock<global::System.Boolean> IsOn()
        {

            return this.IsOn_BagStore ??= new();
            ;
        }
        private global::MockMe.Mocks.ClassMemberMocks.VoidMemberMock? TurnOff_BagStore;
        public global::MockMe.Mocks.ClassMemberMocks.VoidMemberMock TurnOff()
        {

            return this.TurnOff_BagStore ??= new();
            ;
        }
        private global::MockMe.Mocks.ClassMemberMocks.MemberMock<CalculatorType>? get_CalculatorType_BagStore;
        private List<ArgBagWithVoidMemberMock<CalculatorType>>? set_CalculatorType_CalculatorTypeBagStore;
        public global::MockMe.Mocks.ClassMemberMocks.GetSetPropertyMock<CalculatorType> CalculatorType =>
            new(get_CalculatorType_BagStore ??= new(), set_CalculatorType_CalculatorTypeBagStore ??= new());
        [global::System.CodeDom.Compiler.GeneratedCode("MockMe", "1.0.0.0")]
        internal class CalculatorMockCallTracker : MockCallTracker
        {
            private readonly CalculatorMockSetup setup;
            public CalculatorMockCallTracker(CalculatorMockSetup setup)
            {
                this.setup = setup;
            }

            private List<CalculatorMockSetup.Add_Int32_Int32Collection>? Add_Int32_Int32CallStore;
            public global::System.Int32 Add(global::System.Int32 x, global::System.Int32 y)
            {

                return MockCallTracker.CallMemberMock<Add_Int32_Int32Collection, int>(this.setup.Add_Int32_Int32BagStore, this.Add_Int32_Int32CallStore ??= new(), new(x, y));
            }
            private List<CalculatorMockSetup.Multiply_Double_DoubleCollection>? Multiply_Double_DoubleCallStore;
            public global::System.Double Multiply(global::System.Double x, global::System.Double y)
            {

                return MockCallTracker.CallMemberMock<Multiply_Double_DoubleCollection, double>(this.setup.Multiply_Double_DoubleBagStore, this.Multiply_Double_DoubleCallStore ??= new(), new(x, y));
            }
            private List<CalculatorMockSetup.DivideByZero_DoubleCollection>? DivideByZero_DoubleCallStore;
            public void DivideByZero(global::System.Double numToDivide)
            {

                MockCallTracker.CallVoidMemberMock(this.setup.DivideByZero_DoubleBagStore, this.DivideByZero_DoubleCallStore ??= new(), new(numToDivide));
            }
            private int IsOn_CallStore;

            public global::System.Boolean IsOn()
            {
                this.IsOn_CallStore++;
                return MockCallTracker.CallMemberMock(this.setup.IsOn_BagStore);
            }

            private int TurnOff_CallStore;

            public void TurnOff()
            {
                this.TurnOff_CallStore++;
                VoidMockCallTracker.CallVoidMemberMock(this.setup.TurnOff_BagStore);
            }

            private int get_CalculatorType_CallStore;
            private List<CalculatorType>? set_CalculatorType_CalculatorTypeCallStore;
            public CalculatorType CalculatorType
            {
                get
                {

                    this.get_CalculatorType_CallStore++;
                    return MockCallTracker.CallMemberMock(this.setup.get_CalculatorType_BagStore);
                }
                set
                {

                    VoidMockCallTracker.CallVoidMemberMock(this.setup.set_CalculatorType_CalculatorTypeBagStore, this.set_CalculatorType_CalculatorTypeCallStore ??= new(), value);
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCode("MockMe", "1.0.0.0")]
            internal class CalculatorMockAsserter : MockAsserter
            {
                private readonly CalculatorMockSetup.CalculatorMockCallTracker tracker;
                public CalculatorMockAsserter(CalculatorMockSetup.CalculatorMockCallTracker tracker)
                {
                    this.tracker = tracker;
                }

                public global::MockMe.Asserters.MemberAsserter Add(Arg<global::System.Int32> x, Arg<global::System.Int32> y)
                {

                    return GetMemberAsserter(this.tracker.Add_Int32_Int32CallStore, x, y);
                }
                public global::MockMe.Asserters.MemberAsserter Multiply(Arg<global::System.Double> x, Arg<global::System.Double> y)
                {

                    return GetMemberAsserter(this.tracker.Multiply_Double_DoubleCallStore, x, y);
                }
                public global::MockMe.Asserters.MemberAsserter DivideByZero(Arg<global::System.Double> numToDivide)
                {

                    return GetMemberAsserter(this.tracker.DivideByZero_DoubleCallStore, numToDivide);
                }
                public global::MockMe.Asserters.MemberAsserter IsOn() =>
                    new(this.tracker.IsOn_CallStore);

                public global::MockMe.Asserters.MemberAsserter TurnOff() =>
                    new(this.tracker.TurnOff_CallStore);

                public global::MockMe.Asserters.GetSetPropertyAsserter<CalculatorType> CalculatorType =>
                    new(this.tracker.get_CalculatorType_CallStore, this.tracker.set_CalculatorType_CalculatorTypeCallStore);
            }

        }

    }

}
#pragma warning restore
