name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - wiki/**
      - .github/workflows/publishWiki.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
  
  build_and_pack:
    runs-on: ubuntu-latest

    env:
      ContinuousIntegrationBuild: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Build harmony and test runner
      run: |
        dotnet build ./Harmony/Harmony/Harmony.csproj -c ReleaseThin
        dotnet build ./tests/MockMe.Tests.Runner/MockMe.Tests.Runner.csproj -c Release

    - name: Test And Collect CodeCov
      run: |
        dotnet tool install --global dotnet-coverage
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet-coverage collect "dotnet run --project ./tests/MockMe.Tests.Runner/ -c Release --no-build" -f xml -s ./CodeCoverage.runsettings

    - name: Generate report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.3
      with:
        reports: './output.xml'
        targetdir: './tests/TestResults'
        reporttypes: 'lcov'

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        file: ./tests/TestResults/lcov.info
