name: Release to NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Build harmony
      run: dotnet build ./Harmony/Harmony/Harmony.csproj -c ReleaseThin

    - name: Pack nugets
      run: dotnet pack -c Release /p:ContinuousIntegrationBuild=true /p:Version=${{ github.ref_name }} --output .

    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
